import Product from '#models/product'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    // Write your database queries inside the run method
    await Product.createMany([{
      name: 'Kit fan 3 Unidades',
      price: 130.00,
      stocked: 100,
      categoryId: 1,
      subcategoryId: 1,
      approvals: 0,
      imgSrc: '/app/uploads/Gabinetes/',
      description:'kit fan 3 unidades, SuperFrame Cyclone V2, ARGB, 120mm, preto, SF-FN-CYK12AB' ,
    },{
      name: 'Kit fan 3 unidades',
      price: 570.99,
      stocked: 43,
      categoryId: 1,
      subcategoryId: 1,
      approvals: 0,
      imgSrc: '',
      description: 'kit fan 3 unidades, Thermaltake Swafan Ex12, ARGB, 120mm, PWM, branco, CL-F169-PL12SW-A',
    },{
      name: 'Water Cooler DeepCool ',
      price: 900.00,
      stocked: 111,
      categoryId: 1,
      subcategoryId: 1,
      approvals: 0,
      imgSrc: '',
      description: 'Water Cooler DeepCool LT720 WH, ARGB, 360mm, Intel-AMD, White, R-LT720-WHAMNF-G-1',
    },{
      name: 'Water Cooler DeepCool ',
      price: 999.99,
      stocked: 120,
      categoryId: 1,
      subcategoryId: 1,
      approvals: 0,
      imgSrc: '',
      description: 'Water Cooler DeepCool Mystique 360, 360mm, ARGB, Intel/AMD, Tela LCD, Black, R-LX750-BKDSNMP-G-1',
    },{
      name: 'SSD Kingston NV2 1TB',
      price: 339.99,
      stocked: 1100,
      categoryId: 1,
      subcategoryId: 2,
      approvals: 0,
      imgSrc: '',
      description: 'SSD Kingston NV2, 1TB, M.2 NVMe, 2280, Leitura 3500MBs e Gravação 2100MBs, SNV2S/1000G ',
    },{
      name: 'SSD XPG GAMMMIX 1TB',
      price: 659.99,
      stocked: 400,
      categoryId: 1,
      subcategoryId: 2,
      approvals: 0,
      imgSrc: '',
      description: 'SSD XPG GAMMMIX S70 BLADE 1TB, M.2 2280 NVMe, Leitura 7400MBs e Gravação 5500MBs, AGAMMIXS70B-1T-CS',
    },{
      name: 'SSD Kingston A400 480GB',
      price: 240.00,
      stocked: 590,
      categoryId: 1,
      subcategoryId: 2,
      approvals: 0,
      imgSrc: '',
      description: 'SSD Kingston A400, 480GB, Sata III, Leitura 500MBs Gravação 450MBs, SA400S37/480G ',
    },{
      name: 'SSD Adata SU650 240GB',
      price: 139.00,
      stocked: 430,
      categoryId: 1,
      subcategoryId: 2,
      approvals: 31,
      imgSrc: '',
      description: 'SSD Adata SU650, 240GB, Sata III, Leitura 520MBs e Gravação 450MBs, ASU650SS-240GT-R',
    },{
      name: 'HD Western Digital 8TB',
      price: 1759.00,
      stocked: 1400,
      categoryId: 1,
      subcategoryId: 2,
      approvals: 0,
      imgSrc: '',
      description: 'HD Western Digital Purple Surveillance, 8TB, Sata III, 5640RPM, 256MB, WD85PURZ ',
    },{
      name: 'HD Western Digita 1TB',
      price: 340,
      stocked: 990,
      categoryId: 1,
      subcategoryId: 2,
      approvals: 0,
      imgSrc: '',
      description: 'HD Western Digital Blue 1TB, Sata III, 7200RPM, 64MB, WD10EZEX 340reais',
    },{
      name: 'Placa Mãe ASRock B550M',
      price: 1200.00,
      stocked: 139,
      categoryId: 1,
      subcategoryId: 3,
      approvals: 0,
      imgSrc: '',
      description: 'Placa Mãe ASRock B550M Steel Legend, Chipset B550, AMD AM4, MATX, DDR4',
    },{
      name: 'Placa Mãe Asus ROG',
      price: 2600.00,
      stocked: 140,
      categoryId: 1,
      subcategoryId: 3,
      approvals: 0,
      imgSrc: '',
      description: 'Placa Mãe Asus ROG Strix B550-XE Gaming WiFi, Chipset B550, AMD AM4, ATX, DDR4, 90MB17B0-M0EAY0',
    },{
      name: 'Placa Mãe Gigabyte B650M',
      price: 900,
      stocked: 130,
      categoryId: 1,
      subcategoryId: 3,
      approvals: 0,
      imgSrc: '',
      description: 'Placa Mãe Gigabyte B650M Gaming WIFI, Chipset B650, AMD AM5, M-ATX, DDR5',
    },{
      name: 'Placa Mãe Biostar H510MH 2.0',
      price: 459.00,
      stocked: 1220,
      categoryId: 1,
      subcategoryId: 3,
      approvals: 0,
      imgSrc: '',
      description: 'Placa Mãe Biostar H510MH 2.0, Chipset H510, Intel LGA 1200, mATX, DDR4',
    },{
      name: 'Fonte Aerocool KCAS 500W',
      price: 260,
      stocked: 444,
      categoryId: 1,
      subcategoryId: 4,
      approvals: 0,
      imgSrc: '',
      description: 'Fonte Aerocool KCAS 500W, 80 Plus Bronze, PFC Ativo, 59765',
    },{
      name: 'Fonte Be Quiet Pure Power 12 M',
      price: 1300.00,
      stocked: 300,
      categoryId: 1,
      subcategoryId: 4,
      approvals: 0,
      imgSrc: '',
      description: 'Fonte Be Quiet Pure Power 12 M, 1000W, 80 Plus Gold, PFC Ativo, Full Modular, Black, BN523',
    },{
      name: 'Fonte Cooler Master GX III 850W',
      price: 1299.59,
      stocked: 222,
      categoryId: 1,
      subcategoryId: 4,
      approvals: 0,
      imgSrc: '',
      description: 'Fonte Cooler Master GX III 850W, 80 Plus Gold, PCI-E 5.0, PFC Ativo, Full Modular, Black, MPX-8503-AFAG-BWO',
    },{
      name: 'Fonte Corsair RM850x 850W',
      price: 999.99,
      stocked: 230,
      categoryId: 1,
      subcategoryId: 4,
      approvals: 0,
      imgSrc: '',
      description: 'Fonte Corsair RM850x Shift White, 850W, 80 Plus Gold, Full Modular, Branco, CP-9020274-BR',
    },{
      name: 'Memória DDR4 XPG Gammix 8GB',
      price: 115,
      stocked: 130,
      categoryId: 1,
      subcategoryId: 5,
      approvals: 0,
      imgSrc: '',
      description: 'Memória DDR4 XPG Gammix D10, 8GB 3200Mhz, Black, AX4U32008G16A-SB10',
    },{
      name: 'Memória DDR4 Redragon Solar 16GB, ',
      price: 260.00,
      stocked: 2300,
      categoryId: 1,
      subcategoryId: 5,
      approvals: 0,
      imgSrc: '',
      description: 'Memória DDR4 Redragon Solar, RGB, 16GB, 3600Mhz, Black, GM-806',
    },{
      name: 'Memória DDR4 XPG GAMMIX 8GB',
      price: 149.99,
      stocked: 1300,
      categoryId: 1,
      subcategoryId: 5,
      approvals: 0,
      imgSrc: '',
      description: 'Memória DDR4 XPG GAMMIX D35, 8GB, 3200Mhz, White, AX4U32008G16A-SWHD35',
    },{
      name: 'Memória DDR4 Geil Orion RGB 8GB',
      price: 155.99,
      stocked: 1220,
      categoryId: 1,
      subcategoryId: 5,
      approvals: 0,
      imgSrc: '',
      description: 'Memória DDR4 Geil Orion RGB, 8GB, 3200MHz, Red, GAOSR48GB3200C16BSC',
    },{
      name: 'Memória DDR5 Kingston Fury Beast 32GB',
      price: 849.99,
      stocked: 1300,
      categoryId: 1,
      subcategoryId: 5,
      approvals: 0,
      imgSrc: '',
      description: 'Memória DDR5 Kingston Fury Beast',
    },{
      name: 'Processador AMD Ryzen 9 7900X 4.7GHz',
      price: 299.99,
      stocked: 444,
      categoryId: 1,
      subcategoryId: 6,
      approvals: 0,
      imgSrc: '',
      description: 'Processador AMD Ryzen 9 7900X 4.7GHz (5.6GHz Turbo), 12-Cores 24-Threads, AM5, Sem Cooler, 100-100000589WOF',
    },{
      name: 'Processador AMD Ryzen 7 8700G, 4.2GHz',
      price: 1600.00,
      stocked: 122,
      categoryId: 1,
      subcategoryId: 6,
      approvals: 0,
      imgSrc: '',
      description: 'Processador AMD Ryzen 7 8700G, 4.2GHz (5.1GHz Turbo), 8-Cores 16-Threads, AM5, Com Cooler AMD Wraith Stealth, 100-100001236BOX',
    },{
      name: 'Processador AMD Ryzen 7 5700X3D 3.0GHz',
      price: 1449.59,
      stocked: 122,
      categoryId: 1,
      subcategoryId: 6,
      approvals: 0,
      imgSrc: '',
      description: 'Processador AMD Ryzen 7 5700X3D 3.0GHz (4.1GHz Turbo), 8-Cores 16-Threads, AM4, Sem Cooler, 100-100001503WOF',
    },{
      name: 'Processador Intel Core i9 14900KF, 3.6 GHz',
      price: 3499.49,
      stocked: 122,
      categoryId: 1,
      subcategoryId: 6,
      approvals: 0,
      imgSrc: '',
      description: 'Processador Intel Core i9 14900KF, 3.6 GHz (6.0GHz Turbo), 14ª Geração, 24-Cores 32-Threads, LGA 1700, BX8071514900KF',
    },{
      name: 'Teclado Mecânico Gamer MCHOSE K99',
      price: 649.00,
      stocked: 1200,
      categoryId: 2,
      subcategoryId: 7,
      approvals: 0,
      imgSrc: '',
      description: 'Teclado Mecânico Gamer MCHOSE K99, Wireless, Bluetooth, RGB, Switch Hyacinth, ANSI, Layout 98%, Cinza E Azul Celeste, MC-K99-10',
    },{
      name: 'teclado Mecânico Logitech MX',
      price: 1059.99,
      stocked: 111,
      categoryId: 2,
      subcategoryId: 7,
      approvals: 0,
      imgSrc: '',
      description: 'Teclado Mecânico Logitech MX Mechanical Mini, Sem Fio, Bluetooth, Easy-Switch, 920-010783',
    },{
      name: 'Mouse Gamer PCYES Zyron RGB',
      price: 95.99,
      stocked: 300,
      categoryId: 1,
      subcategoryId: 7,
      approvals: 0,
      imgSrc: '',
      description: 'Mouse Gamer PCYES Zyron, RGB, 6 Botões, 12800 DPI, White, PMGZRGBW',
    },{
      name: 'Mouse Gamer Redragon Plank RGB',
      price: 99.59,
      stocked: 298,
      categoryId: 2,
      subcategoryId: 7,
      approvals: 0,
      imgSrc: '',
      description: 'Mouse Gamer Redragon Plank RGB, 16000 DPI, 9 Botões Programáveis, Black, M812-RGB',
    },{
      name: 'Mousepad Gamer Ninja',
      price: 14.50,
      stocked: 2000,
      categoryId: 2,
      subcategoryId: 8,
      approvals: 0,
      imgSrc: '',
      description: 'Mousepad Gamer Ninja, Control, Médio 400x300mm, Grey, MPGN-GREY-M',
    },{
      name: 'Mousepad Gamer Thermaltake Sports',
      price: 149.99,
      stocked: 122,
      categoryId: 2,
      subcategoryId: 8,
      approvals: 0,
      imgSrc: '',
      description: 'Mousepad Gamer Thermaltake Sports Draconem RGB Cloth Edition, Preto, MP-DCM-RGBSMS-01',
    },{
      name: 'Mousepad Gamer Marvo RGB',
      price: 65.99,
      stocked: 222,
      categoryId: 2,
      subcategoryId: 8,
      approvals: 0,
      imgSrc: '',
      description:'Mousepad Gamer Marvo, RGB, Hub USB, Control, Grande, 800x300mm, MG011',
    },{
      name: 'Mousepad Vinik MPG-10P',
      price: 34.50,
      stocked: 222,
      categoryId: 2,
      subcategoryId: 8,
      approvals: 0,
      imgSrc: '',
      description: "Mousepad Vinik MPG-10P, 220X180X3mm, Com Apoio para o Pulso Feito Em Gel, Black, MPG-10P ",
    },{
      name: 'Headset Gamer Fifine H6',
      price: 195.99,
      stocked: 234,
      categoryId: 2,
      subcategoryId: 9,
      approvals: 44,
      imgSrc: '',
      description: 'Headset Gamer Fifine H6, 7.1 Surround, Drivers de 50mm, RGB, USB, Black',
    },{
      name: 'Headset Gamer Logitech Astro A10',
      price: 449.99,
      stocked: 122,
      categoryId: 2,
      subcategoryId: 9,
      approvals: 22,
      imgSrc: '',
      description: 'Headset Gamer Logitech Astro A10, Para Xbox, White/Green, 939-001854 ',
    },{
      name: 'Fone de Ouvido Marvo BE-889',
      price: 149.99,
      stocked: 2222,
      categoryId: 2,
      subcategoryId: 9,
      approvals: 0,
      imgSrc: '',
      description: 'Fone de Ouvido Marvo BE-889, Sem Fio, Stereo, Black ',
    },{
      name: 'Headset Gamer Sem Fio Sony',
      price: 869.49,
      stocked: 222,
      categoryId: 2,
      subcategoryId: 9,
      approvals: 22,
      imgSrc: '',
      description: 'Headset Gamer Sem Fio Sony Pulse 3D, USB, PS5, CFI-ZWH2L',
    },{
      name: 'Microfone Gamer Fifine',
      price: 277.99,
      stocked: 122,
      categoryId: 2,
      subcategoryId: 10,
      approvals: 33,
      imgSrc: '',
      description: 'Microfone Gamer Fifine Ampligame A6T, RGB, USB, Black, Com Braço Articulado',
    },{
      name: 'Microfone JBL Quantum Stream RGB',
      price: 295.39,
      stocked: 211,
      categoryId: 2,
      subcategoryId: 10,
      approvals: 0,
      imgSrc: '',
      description: 'Microfone JBL Quantum Stream, RGB, Otimizado pra PC/MAC/PS5/PS4/Nintendo Switch, Metálico, JBLQSTREAMBLK ',
    },{
      name: 'Microfone Gamer Havit GK58B',
      price: 48.00,
      stocked: 222,
      categoryId: 2,
      subcategoryId: 10,
      approvals: 0,
      imgSrc:'',
      description: 'Microfone Gamer Havit GK58B, RGB, USB, Preto',
    },{
      name: 'Microfone Gamer Fifine Ampligame',
      price: 379.99,
      stocked: 222,
      categoryId: 2,
      subcategoryId: 10,
      approvals: 0,
      imgSrc: '',
      description: 'Microfone Gamer Fifine Ampligame A8 Plus, RGB, USB, Black',
    },{
      name: 'Cadeira Gamer Ninja Jiraya',
      price:420.00,
      stocked: 221,
      categoryId: 3,
      subcategoryId: 11,
      approvals: 44,
      imgSrc: '',
      description: 'Cadeira Gamer Ninja Jiraya, Branco e Preto',
    },{
      name: 'Cadeira Gamer SuperFrame Godzilla',
      price: 450.99,
      stocked: 211,
      categoryId: 3,
      subcategoryId: 11,
      approvals: 0,
      imgSrc: '',
      description: 'Cadeira Gamer SuperFrame Godzilla, Reclinável, Preto e Vermelho',
    },{
      name: 'Cadeira Gamer Duex DX9026B',
      price: 429.99,
      stocked: 111,
      categoryId: 3,
      subcategoryId: 11,
      approvals: 2,
      imgSrc: '',
      description: 'Cadeira Gamer Duex DX9026B',
    },{
      name: 'Cadeira Gamer Terabyte',
      price: 699.99,
      stocked: 222,
      categoryId: 3,
      subcategoryId: 11,
      approvals: 2,
      imgSrc: '',
      description: 'Cadeira Gamer Terabyte Vision, Reclinável, 2D, Preto e Azul ',
    },{
      name: 'Gabinete Gamer Be Quiet',
      price: 449.59,
      stocked: 221,
      categoryId: 3,
      subcategoryId: 12,
      approvals: 44,
      imgSrc: '',
      description: 'Gabinete Gamer Be Quiet Pure Base 500 DX, Mid Tower, ATX, ARGB, Vidro Temperado, Com 3 Fans, Preto, BGW37',
    },{
      name: 'Gabinete Gamer Redragon',
      price: 449.29,
      stocked: 332,
      categoryId: 3,
      subcategoryId: 12,
      approvals: 31,
      imgSrc: '',
      description: 'Gabinete Gamer Redragon Wideload Pro, Mid Tower, Vidro Temperado, ATX, Black, Sem Fonte, Sem Fan, CA-604B-PRO',
    },{
      name: 'Gabinete Gamer NZXT',
      price: 1700.00,
      stocked: 233,
      categoryId: 3,
      subcategoryId: 12,
      approvals: 12,
      imgSrc: '',
      description: 'Gabinete Gamer NZXT H9 Elite, Mid Tower, Vidro Temperado, Black, ATX, Sem Fonte, Com 4 Fans, CM-H91EB-01',
    },{
      name: 'Gabinete Gamer Montech X3',
      price: 379.00,
      stocked: 222,
      categoryId: 3,
      subcategoryId: 12,
      approvals: 2,
      imgSrc: '',
      description: 'Gabinete Gamer Montech X3 Glass, Mid Tower, Black, ATX, Com 6 Fans, Vidro Temperado',
    },{
      name: 'Monitor Gamer Acer Nitro 31,5 Pol',
      price: 1559.39,
      stocked: 2212,
      categoryId: 3,
      subcategoryId: 13,
      approvals: 22,
      imgSrc: '',
      description: 'Monitor Gamer Acer Nitro EDT320Q, 31,5 Pol, Curvo, FHD, 180Hz, 1Ms, FreeSync, Preto, UM.JE0AA.305',
    },{
      name: 'Monitor Gamer AOC Agon 4 Pro 27 Pol',
      price: 4339.39,
      stocked: 2212,
      categoryId: 3,
      subcategoryId: 13,
      approvals: 0,
      imgSrc: '',
      description: 'Monitor Gamer AOC Agon 4 Pro, 27 Pol, 4K UHD, IPS, 144Hz, 1ms, HDR600, 133% sRGB, G-Sync, HDMI/DP, AG274UXP',
    },{
      name: 'Monitor Gamer LG 29 Pol ',
      price: 3659.39,
      stocked: 2212,
      categoryId: 3,
      subcategoryId: 13,
      approvals: 22,
      imgSrc: '',
      description: 'Monitor Gamer LG, 29 Pol, UltraWide, Full HD, IPS, 99% sRGB, HDR, FreeSync, 29WL500-B',
    },{
      name: 'Monitor Gamer Samsung T35F 24 Pol',
      price: 659.39,
      stocked: 222,
      categoryId: 3,
      subcategoryId: 13,
      approvals: 46,
      imgSrc: '',
      description: 'Monitor Gamer Samsung T35F, 24 Pol, Full HD, IPS, HDMI/VGA, LF24T350FHLMZD',
    }])
  }
}